// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `copy_tile_output`, `extract_tile_with_reflect_pad`, `reflect_coord`, `run_inference`

/// ort 超分：读 input_path 图片 → Real-CUGAN tile 推理 → 写 output_path（2x PNG）。
///
/// [dylib_path] 外挂 onnxruntime 动态库路径（load-dynamic）。
///
/// 命名 `upscale_ort`（→ Dart `upscaleOrt`）避免与调用方 `upscale` 方法同名递归。
Future<void> upscaleOrt({
  required String inputPath,
  required String outputPath,
  required String modelPath,
  required String dylibPath,
}) => RustLib.instance.api.crateApiUpscaleUpscaleOrt(
  inputPath: inputPath,
  outputPath: outputPath,
  modelPath: modelPath,
  dylibPath: dylibPath,
);
